export const PRODUCT_PACKAGES = [
  {
    id: 1,
    icon: "/companyR.svg",
    title: "Pre-Diligence Assessment",
    sub: "Investor-simulated external assessment of your company",
    desc: "See how your company would be assessed by an external investor based on publicly available information and market signals.",
    badge: "",
    tooltip: "Founders who want a clear, unbiased view of how their company currently comes across to investors.",
    priceOneOff: "£300",
    priceAnnual: "£210",
    perAnnual: "/ year",
    save: "Save 30%",
    // features: [
    //     { icon: "/clock.svg", text: "24h delivery" },
    //     { icon: "/file.svg", text: "PDF & Excel formats" },
    //     { icon: "/tick.svg", text: "Email support" },
    // ],
    features: [
      { icon: "/greentick.svg", text: "Investor-style company overview" },
      { icon: "/greentick.svg", text: "Product & technology assessment" },
      {
        icon: "/greentick.svg",
        text: "Traction, performance, and validation signals",
      },
      { icon: "/greentick.svg", text: "Team and governance assessment" },
      {
        icon: "/greentick.svg",
        text: "Financial position and runway analysis",
      },
      {
        icon: "/greentick.svg",
        text: "Key risks and unresolved information gaps",
      },
    ],
  },
  {
    id: 2,
    icon: "/images/analysis.png",
    title: "Competitive Positioning Assessment",
    sub: "Investor-simulated comparison against peers and competitors",
    desc: "Understand how investors are likely to compare you with other companies in the same space — and where you stand out or fall behind.",
    badge: "",
    tooltip: "Founders preparing for investor conversations and wanting to sharpen their positioning.",
    priceOneOff: "£500",
    priceAnnual: "£350",
    perAnnual: "/ year",
    save: "Save 30%",
    // features: [
    //     { icon: "/greentick.svg", text: "Quarterly updates" },
    //     { icon: "/greentick.svg", text: "Priority support" },
    //     { icon: "/greentick.svg", text: "Data archive access" },
    // ],
    features: [
      {
        icon: "/greentick.svg",
        text: "Everything in Pre-Diligence Assessment",
      },
      {
        icon: "/greentick.svg",
        text: "Competitive landscape and peer grouping",
      },
      {
        icon: "/greentick.svg",
        text: "Relative positioning on product, traction, and maturity",
      },
      {
        icon: "/greentick.svg",
        text: "Comparison of differentiation claims vs competitors",
      },
      {
        icon: "/greentick.svg",
        text: "Narrative strengths and weaknesses in a competitive context",
      },
    ],
  },
  {
    id: 3,
    icon: "/images/companyD.png",
    title: "Fundraising Readiness Diagnostic",
    sub: "Investor-simulated diligence diagnostic",
    desc: "Stress-test your readiness for fundraising by simulating the questions and scrutiny investors will apply during diligence.",
    badge: "Not investment advice",
    tooltip: "Founders actively preparing to raise capital and wanting to identify weaknesses before investors do.",
    priceOneOff: "£300",
    priceAnnual: "£210",
    perAnnual: "/ year",
    save: "Save 30%",
    // features: [
    //     { icon: "/clock.svg", text: "3-day turnaround" },
    //     { icon: "/file.svg", text: "Financial model" },
    //     { icon: "/tick.svg", text: "Raw data access" },
    // ],
    features: [
      {
        icon: "/greentick.svg",
        text: "Everything in Competitive Positioning Assessment",
      },
      {
        icon: "/greentick.svg",
        text: "Structured, section-by-section diligence question set",
      },
      { icon: "/greentick.svg", text: "Coverage across:" },
      { icon: "/dot.svg", text: "Team & governance" },
      { icon: "/dot.svg", text: "Product & technology" },
      { icon: "/dot.svg", text: "Market & competition" },
      { icon: "/dot.svg", text: "Traction & metrics" },
      { icon: "/dot.svg", text: "Financials & runway" },
      { icon: "/dot.svg", text: "Legal, IP, and compliance" },
      { icon: "/dot.svg", text: "ESG and reputation" },
      {
        icon: "/greentick.svg",
        text: "Identification of high-risk, under-documented, or contradictory areas",
      },
    ],
  },
];

export const PRODUCT1_PACKAGES = [
  {
    id: 1,
    icon: "/companyR.svg",
    title: "Company Research Report",
    desc: "Comprehensive analysis of company performance, market position, and strategic insights.",
    priceOneOff: "£300",
    priceAnnual: "£210",
    perAnnual: "/ year",
    save: "Save 30%",
    features: [
      { icon: "/clock.svg", text: "24h delivery" },
      { icon: "/file.svg", text: "PDF & Excel formats" },
      { icon: "/tick.svg", text: "Email support" },
    ],
  },
  {
    id: 2,
    icon: "/images/Banalysis.png",
    title: "Competitive Analysis",
    desc: "In-depth competitive landscape analysis with market positioning and strategies.",
    priceOneOff: "£500",
    priceAnnual: "£350",
    perAnnual: "/ year",
    save: "Save 30%",
    features: [
      { icon: "/Gaccess.svg", text: "Quarterly updates" },
      { icon: "/Greports.svg", text: "Priority support" },
      { icon: "/Ganalysis.svg", text: "Data archive access" },
    ],
  },
  {
    id: 3,
    icon: "/images/fund.png",
    title: "Company Deep Dive",
    desc: "Detailed examination of company operations, financials, and growth opportunities.",
    priceOneOff: "£300",
    priceAnnual: "£210",
    perAnnual: "/ year",
    save: "Save 30%",
    features: [
      { icon: "/clock.svg", text: "3-day turnaround" },
      { icon: "/file.svg", text: "Financial model" },
      { icon: "/tick.svg", text: "Raw data access" },
    ],
  },
];

export const BUNDLE_PACKAGES = [
  {
    id: "market",
    icon: "/images/marketing.png",
    title: "Market Analysis Bundle",
    desc: "Complete market intelligence package",
    priceOneOff: "£900",
    priceYearly: "£800",
    oldPriceYearly: "£900",
    saveBadge: "SAVE £100",
    headerIcon: "/images/goldstar.png",
    headerLabel: "Annual Benefits:",
    features: [
      "Quarterly report updates",
      "Priority support access",
      "Market trend alerts",
    ],
    showSave30: true,
  },
  {
    id: "fundraising",
    icon: "/images/fundraising.png",
    title: "Fundraising Readiness",
    desc: "Complete package for investors",
    priceOneOff: "£900",
    priceYearly: "£650",
    oldPriceYearly: "£900",
    saveBadge: "SAVE £250",
    headerIcon: "/images/include.png",
    headerLabel: "What's Included:",
    features: [
      "Company Research Report",
      "Competitive Analysis Report",
      "Company Deep Dive",
    ],
    showSave30: false,
  },
];

export const VAT_RATE = 0;
